# Use official RabbitMQ management alpine image as base
FROM rabbitmq:management-alpine

# Set environment variables for RabbitMQ
ENV RABBITMQ_DEFAULT_USER=rabbitmq \
    RABBITMQ_DEFAULT_PASS=rabbitmq

# Create volume for persistent data
VOLUME ["/var/lib/rabbitmq"]

# Expose ports
# 5672: AMQP protocol port
# 15672: Management UI port
EXPOSE 5672 15672