FROM postgres:16

# Set environment variables for Postgres
ENV POSTGRES_USER=airflow \
    POSTGRES_PASSWORD=airflow \
    POSTGRES_DB=airflow

# Copy initialization script
COPY init-db.sh /docker-entrypoint-initdb.d/init-db.sh

# Ensure the script is executable
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# Expose Postgres port
EXPOSE 5432